import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../Components/Layout';
// // import cv from "../public/CV_Josephine_Geoghegan.pdf";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Front End Interview Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Layout>
  <main className={styles.main}>
    <h1>Who am I?</h1>
    <p>
      My name is Josephine. 
      I am looking for new opportunities 
      as a front end developer.
    </p>
    <button className={styles.buttonsHome}>
      <a href="https://drive.google.com/uc?export=download&id=1Mh8_npdnOG02JJpQobE6_z4VkCb_VtxE" download>
        Download my CV here
      </a>
    </button>
    <h1>What is this website?</h1>
    <p>
      This website is based on a repository
      of interview questions for front end developers. 
      I am putting together answers I found online to 
      some of the questions. This is mostly to teach 
      myself and give potential employers a better idea of how I work. 
    </p>
    <button className={styles.buttonsHome}>
      <a href="https://github.com/h5bp/Front-end-Developer-Interview-Questions" target="_blank">
        Check out the repo
      </a>
    </button>
  </main>
      <footer style={{display: "hidden"}}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
  </Layout>
    </div>
  )
}
